version: 2
registries:
  npm-registry-npm-pkg-github-com:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: "${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
  open-pull-requests-limit: 99
  reviewers:
  - scherermichael
  versioning-strategy: increase
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: "@sealsystems/eslint-config-es"
    versions:
    - ">= 0"
  - dependency-name: "@sealsystems/mocha"
    versions:
    - ">= 0"
  - dependency-name: "@sealsystems/semantic-release"
    versions:
    - ">= 0"
  - dependency-name: flaschenpost
    versions:
    - 4.3.35
    - 4.3.36
    - 4.3.37
    - 5.0.0
    - 5.0.1
    - 5.0.10
    - 5.0.11
    - 5.0.12
    - 5.0.13
    - 5.0.14
    - 5.0.15
    - 5.0.16
    - 5.0.17
    - 5.0.18
    - 5.0.19
    - 5.0.2
    - 5.0.21
    - 5.0.24
    - 5.0.3
    - 5.0.4
    - 5.0.5
    - 5.0.6
    - 5.0.7
    - 5.0.8
    - 5.0.9
  commit-message:
    prefix: chore
    prefix-development: no-release
    include: scope
  registries:
  - npm-registry-npm-pkg-github-com
