name: publish

on:
  release:
    types: [published]

jobs:
  Publish:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.18.1 for publishing to npm.pkg.github.com
        uses: actions/setup-node@v2
        with:
          node-version: 14.18.1
          registry-url: "https://npm.pkg.github.com"

      - name: Cache Node.js modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-14.18.1-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{ secrets.CI_TOKEN }}

      - name: Publish on npm.pkg.github.com
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js 14.18.1 for publishing to npmjs.org
        uses: actions/setup-node@v2
        with:
          node-version: 14.18.1
          registry-url: "https://registry.npmjs.org"
          scope: "@sealsystems"

      - name: Publish on npmjs.org
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
